language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_STATIC_ANALYSIS=0
    - TASK_TESTS_COVERAGE=0

matrix:
  include:
    - php: "7.4"
      env:
        - TASK_STATIC_ANALYSIS=0 # set to 1 to enable static analysis
        - TASK_TESTS_COVERAGE=1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      pecl install ast
    fi

before_script:
  - php --version
  - composer --version
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
        PHPUNIT_COVERAGE_FLAG="--coverage-clover=coverage.clover"
    fi

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose $PHPUNIT_COVERAGE_FLAG
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      composer phan
    fi
  - |
    if [ $TASK_STATIC_ANALYSIS == 1 ]; then
      cat analysis.txt
    fi

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

notifications:
  slack:
    -
      rooms:
        -
          secure: BthuPKqpxt6sLLFD8ZZvYeAOhXrM5HrfXCPerlgdrz6diUL0TOP4t/ZUrZiKx+fwopCB9QETzmmkk+bczD1TImcfLbUgG6Eydu+UxpodunQ3CNhJb5jdi4Xq3ddl/6B7zbjpvptz0DAkmXsADvx3/1NlNB+DAGMH2jAHaElN+4ko0fVGQWcALMrf+ohzhHpxreMBbk6uvczJcTQt4WG2Ya8e8lSsz3+BQUrlezB1TS2lqZ4Uqg063F4+GVoeXNwszdEZC68XYLwTnH2rPajL1W+w8RNevspjvuDoGc5y/eG069OFBnRJwiK9HVMsyLi6XFgHPUddn/n+/wbYjASh6218wSUpq+FkfEPBG5epObfV5QMtbA2pSU2klMid5CI74pMvmvgl/CpL8lk5Fd+VVj+x/hiGMGM4glKPBRWf3gBFT3j6D25fWyC/fAqK9kOoPPg22qtS6DmqXgCiYXulePMtq3yepHAsrMscRTdpzPLgwgoYL/dWunMCF7GgD9IM/7u0aF0ufe2NowoqOTgPnRF5ZDw43v20tlELerst1JBAP3+de7QfbUzJyWL/DwfCiPhrqPXnU7Xd+1TKcwz6hownM+yIzZWMLCwnIy5h4MezDwn8ijz+n5lWtR3jgLKkI/CZ5MhE9Cz6QIEN+qBFUuIESai9LwqIEvm0CMftAWk=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: TPoE0TEhwQLZFvROTC7qsvdZ54HVruTqeKyL2Mbt3UE7OwyoEZTsWdCFMtIZNp2UOEqFb7Gc9/EnWE2JZx6/oDO173wT6SoV1hAIygRshxTLGNuEnfeESvMlI1yId7/vFAaBA9fFOrdQsUrItitQGZNagDtt8n92UggH7QBLTvCoMT3T5/KFBcaDqapS/afqg9X6606F2j8595xcUoKMZhcsmDrn/eIPncX0yIZCBB/R7Hw4Y/ajR+OG3/5D46+F4yQwx3BqDKLo+UkOofz70qyD6eJWldaekYrNn0Jn2/4/kfPDkIDI79wxeoD0LUW1JGTJC3IhQJfFtCRODUipyG62o+FnCZyMuI9Pqw86vIvVhpA0Gu8WEv/UIJ8C/yAR+XuaDO1efVBuHjyVTTulQRIR6BlvBtPUOmMr+5Nf4kWTONqB9S0vLS5o3g9yERoHEC/j2s1LPdmBqov4R+m2VvwL4e1649GKHBeHjn6JvzNFXr0pT7/QOKQ5zYiba4zQbMBpASKhQxZfBoBxA0w23v7zQ37eELxyXaxx8z8xBhgg9HD21BWaJQOdXg9UG4w90mpw7h28Dyc3wL1G3844WVniFremsM83I/y2JGuR0TMD8ZenTqA+lH1wY0OKRPn5ChhpF5LtwMCOh2jwAcOXhzG61yc/fh8gFrh8sz56iRA=
      on_success: never
      on_failure: always
      on_pull_requests: false
